### ISSUE TITLE
issue in beghr and endhr

### ISSUE THREAD

**Issue by mipademiao** [EAirPeter/HPS-OptimalTouring-Arch#1]
https://github.com/EAirPeter/HPS-OptimalTouring-Arch/blob/da03736cd7caaf6ccbd56fc50ac1ab381257b378/OptimalTour.py#L101

The hour read in will be overwritten.
please fix this by using 
`    self.beghr = [[0 for i in range(n_site)] for j in range(n_day)]
    self.endhr = [[0 for i in range(n_site)] for j in range(n_day)]`

**Comment by EAirPeter** [comment]
It is now fixed in f8ff74220e77cf316bb14ccf6048081387833205. Thank you for pointing this out.
